#!/usr/bin/env python3
"""Quality-gated ETF publisher with separate early/complete snapshots."""

from __future__ import annotations

import argparse
import copy
import json
import os
import sqlite3
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Mapping, Tuple

from etf_ops import load_registry, structured_log, validate_snapshot


WORKSPACE = Path(os.getenv("ETF_WORKSPACE", str(Path.home() / ".etf-skill" / "workspace")))
JSON_SRC = Path(os.getenv("ETF_SNAPSHOT_PATH", str(WORKSPACE / "ETF三因子分析-v7.json")))
LEGACY_TARGET = "src/data/etf-three-factor-latest.json"
EARLY_TARGET = "src/data/etf-three-factor-early-latest.json"
COMPLETE_TARGET = "src/data/etf-three-factor-complete-latest.json"
STATUS_TARGET = "src/data/etf-three-factor-status.json"


def _top_historical(workspace: Path) -> List[Dict[str, Any]]:
    db_path = workspace / "etf_history.db"
    if not db_path.exists():
        return []
    rows: List[Dict[str, Any]] = []
    try:
        conn = sqlite3.connect(str(db_path))
        for row in conn.execute(
            """
            SELECT date, code, name, composite_prob, vol_prob, dir_prob, share_prob,
                   change_pct, shares_delta_pct, signal_level
            FROM etf_daily
            WHERE composite_prob >= 40
            ORDER BY composite_prob DESC
            LIMIT 20
            """
        ):
            rows.append({
                "date": row[0], "code": row[1], "name": row[2],
                "cp": row[3], "vp": row[4], "dp": row[5], "sp": row[6],
                "chg": row[7], "shares_delta_pct": row[8], "level": row[9],
            })
        conn.close()
    except Exception as exc:
        structured_log("top_historical_failed", error=str(exc)[:300])
    return rows


def build_publish_files(data: Dict[str, Any], registry: Mapping[str, Any], workspace: Path = WORKSPACE) -> tuple[str, Dict[str, str], Dict[str, Any]]:
    # Normalize every published artifact to schema v2.  Identity fields are
    # generated by the registry-driven runner and reasserted here so old manual
    # runs are upgraded before the strict quality check.
    enriched = copy.deepcopy(data)
    enriched["schema_version"] = 2
    target_date = enriched.get("target_date")
    latest = enriched.get("latest") if isinstance(enriched.get("latest"), dict) else {}
    for code, row in latest.items():
        if isinstance(row, dict):
            row.setdefault("source_code", str(code))
            row.setdefault("source_date", row.get("d"))
    report = validate_snapshot(enriched, registry, phase="auto")
    if report["status"] == "unhealthy":
        raise ValueError(f"ETF quality gate rejected snapshot: {json.dumps(report['issues'], ensure_ascii=False)}")
    phase = str(report["phase"])
    enriched["run_type"] = phase
    enriched["published_at"] = datetime.now().astimezone().isoformat(timespec="seconds")
    enriched["data_quality"] = report
    enriched["top_historical"] = _top_historical(workspace)
    content = json.dumps(enriched, ensure_ascii=False, indent=2) + "\n"
    status = {
        "schema_version": 1,
        "status": report["status"],
        "phase": phase,
        "target_date": target_date,
        "published_at": enriched["published_at"],
        "metrics": report["metrics"],
        "issues": report["issues"],
    }
    files = {
        STATUS_TARGET: json.dumps(status, ensure_ascii=False, indent=2) + "\n",
        EARLY_TARGET if phase == "early" else COMPLETE_TARGET: content,
    }
    # The legacy path remains the last-known-good complete snapshot. Early data
    # never overwrites it, so the public page cannot regress from 12/12 to 0/12.
    if phase == "complete":
        files[LEGACY_TARGET] = content
    return phase, files, report


def main() -> int:
    parser = argparse.ArgumentParser(description="Publish validated ETF snapshot")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--source", default=str(JSON_SRC))
    parser.add_argument("--registry", default=os.getenv("ETF_REGISTRY_PATH", ""))
    args = parser.parse_args()
    source = Path(args.source)
    if not source.exists():
        print(f"[etf-publish] source JSON not found: {source}", file=sys.stderr)
        return 1
    try:
        with source.open(encoding="utf-8") as handle:
            data = json.load(handle)
        registry = load_registry(args.registry)
        phase, file_map, report = build_publish_files(data, registry, source.parent)
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        structured_log("publish_blocked", error=str(exc)[:1000])
        return 3
    structured_log("publish_gate_passed", phase=phase, target_date=data.get("target_date"), metrics=report["metrics"])
    if args.dry_run:
        print(json.dumps({"ok": True, "phase": phase, "files": sorted(file_map), "quality": report}, ensure_ascii=False, indent=2))
        return 0

    token = os.getenv("GITHUB_TOKEN", "").strip()
    if not token:
        print("[etf-publish] missing GITHUB_TOKEN", file=sys.stderr)
        return 1
    sys.path.insert(0, "/opt/wind-recap")
    from publisher import _push_via_github_api

    owner, repo = os.getenv("GITHUB_REPO", "lzf00/zorotreeking").split("/", 1)
    branch = os.getenv("GITHUB_BRANCH", "main")
    message = f"auto: ETF {phase} {data.get('target_date', datetime.now().strftime('%Y-%m-%d'))}"
    files: List[Tuple[str, str]] = sorted(file_map.items())
    if not _push_via_github_api(owner, repo, branch, files, message, token):
        structured_log("publish_failed", phase=phase, target_date=data.get("target_date"))
        return 2
    structured_log("publish_success", phase=phase, target_date=data.get("target_date"), files=[path for path, _ in files])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
